### PR TITLE
URGENT bugfix

### LINKED ISSUE #591: 0.20 generates big data file and crashes when trying to upload data
I had a long trip and I took collect more data.  It worked relatively fine for the first ~2000 data reports. 

Disclaimer: My Internet connection is quite bad at this moment, so I have not  been able to search properly. So, please bear with me.

At some point I got a notification of low internal space.  I had left ~20 MB.  I cleared data from some applications (like Firefox), I made ~60 MB.  MozStumbler had around 16MB, considering the history of thousands reports it should have been more than enough.

After I while I noticed that MozStumbler stopped silently to collect data. I re-started every time.  That is, until I noticed I had ~1900 pending reports and I tried to upload it manually and it crashed.

So, I enabled to upload only on WiFi and MozStumbler started to collect data continuously again. Until again I was running out of space.  This was is bad sympton, but I uninstalled several other applications to make space and continue tracking.

Long story short: MozStumbler whent from 16MB to 106MB of data in less than one day. I ran out of space and I don't know how to extract manually to inspect it.  I have 4700 observations that can't be uploaded because MozStumbler crashes.

I wish MozStumbler could store the data in the SD, like I can do with other applications.

For context: I have a Nexus 1 with Cynamodgen. I used the file manager to locate a file, with no luck.  And no luck by grepping in the source code.

In short, there are 3 problems:
- Crash when uploading a file (maybe the data storage got corrupted at some point)
- Big increase of the data file between 0.19 and 0.20 (I hardly believe it could have collected 3 times (or more) data than I had done in months)
- No possibility to store the data in an external storage where to back it up (maybe I am missing something).

### PR DESCRIPTION
**Pull request by tamcap**
We never cleaned up the mCellData and mWifiData  after reading from them - making them become HUGE and exponentially increasing storage necessary by MozStumbler by having thousands if not millions of duplicates.

I think this should do the trick. Fixes #591. Please merge & release ASAP.

### CODE REVIEW

File: src/org/mozilla/mozstumbler/Reporter.java [hunk 1]
```diff
@@ -146,7 +146,9 @@ private void reportCollectedLocation() {
         }
 
         Collection<CellInfo> cells = mCellData.values();
+        mCellData.clear();
         Collection<ScanResult> wifis = mWifiData.values();
+        mWifiData.clear();
```
Comment (illarionov) [inline src/org/mozilla/mozstumbler/Reporter.java]: I think this should be somewhere later. The Collection returned values() is backed by the map so changes to the map are reflected in the collection.

Comment (tamcap) [inline src/org/mozilla/mozstumbler/Reporter.java]: ugh, i just assumed it was a simple copy

File: src/org/mozilla/mozstumbler/Reporter.java [hunk 2]
```diff
@@ -189,7 +190,8 @@ private void reportCollectedLocation() {
                 Log.w(LOGTAG, "JSON exception while serializing wifi data: " + exc);
             }
         }
-
+        mCellData.clear();
```
Comment (tamcap) [inline src/org/mozilla/mozstumbler/Reporter.java:193]: @illarionov - that should be late enough :anguished:

**Comment by eggpi** [comment]
I don't think I'm qualified to do a release, but the code looks good to me. Can you please squash your changes into a single commit?

**Comment by tamcap** [comment]
:+1:

**Comment by Djfe** [comment]
Does this fix #408 as well?
If the issue was older than one version then that is likely.

I guess nobody looked further into it since the gzipping reduced the upload size greatly (which makes sence since the data has been duplicated...)
Nobody reported issues about the internal data usage after gzipping was introduced for the upload

**Comment by tamcap** [comment]
I don't think so. High data usage was more of an anomaly instead of a
regular occurrence.

**Comment by Djfe** [comment]
Well than the old issue could be closed, I would say.

**Comment by garvankeeley** [comment]
I started by pulling the current release. Just catching up on this issue right now.
