### PR TITLE
Fix wifi only observation point

### LINKED ISSUE #1611: wifi-only dots aren't drawn green
This is recent regression, I don't know since when though
I noticed it first in 1.7.11, but it could have been earlier as well:

Wifi-Only reports get green dots instead of purple ones on the map

how I know that this is the case:
the log only shows wifi data but no cell data at all for these reports

### PR DESCRIPTION
**Pull request by cascheberg**
Fixes #1611 
The problem is that an exception is thrown when the cell count is set, so the wifi count is never set. Regression since 1170ed029e91fe6b45c4c30d41e23ae17a828303

### CODE REVIEW

**Comment by crankycoder** [comment]
Test case please

**Comment by Djfe** [comment]
thx for the fix! ;)
is an NPE the only bad thing that could happen, or was there another reason for the try-catch block?

and wouldn't it be better to fix ichnaeaQueryObj.getJSONArray, so that it doesn't return null in case that there are no cells/wifis available but an empty array?

**Comment by cascheberg** [comment]
@crankycoder Added tests for setting counts in `ObservationPoint`.

@Djfe I did not want to modify the `toMLSGeosubmit` method to always add an empty array because I wasn't sure about negative impacts regarding client-server communication.

**Comment by Djfe** [comment]
@cascheberg Is `ichnaeaQueryObj.getJSONArray` used in `toMLSGeosubmit` as well or why?

File: android/src/main/java/org/mozilla/mozstumbler/client/mapview/ObservationPoint.java [hunk 1]
```diff
@@ -58,12 +59,11 @@ public void setMLSQuery(StumblerBundle stumbleBundle) {
     }
 
     public void setCounts(JSONObject ichnaeaQueryObj) {
-        try {
-            mCellCount = ichnaeaQueryObj.getJSONArray(DataStorageContract.ReportsColumns.CELL).length();
-            mWifiCount = ichnaeaQueryObj.getJSONArray(DataStorageContract.ReportsColumns.WIFI).length();
-        } catch (JSONException ex) {
-            Log.w(LOG_TAG, "Unable to set count length: " + ex.toString());
-        }
+        JSONArray cells = ichnaeaQueryObj.optJSONArray(DataStorageContract.ReportsColumns.CELL);
```
Comment (crankycoder) [inline android/src/main/java/org/mozilla/mozstumbler/client/mapview/ObservationPoint.java:62]: Nice. I had no idea that `getJSONArray` and `optJSONArray` both exist.

**Comment by cascheberg** [comment]
@Djfe [JSONObject](http://developer.android.com/reference/org/json/JSONObject.html) is provided by the Android API, so you cannot change it's behavior.
But `toMLSGeosubmit` is assembling the structure of the `ichnaeaQueryObj`, so you could modify it to always put an empty `JSONArray` at that index, which I did not want to do.
