### PR TITLE
Minor fixes

### LINKED ISSUE #1436: paused mode should set gps/wifi/cell values to zero
this is an issue that was brought up in #1322

since the device isn't scanning anything in paused mode those values probably should be set to zero to avoid confusion

### PR DESCRIPTION
**Pull request by cascheberg**
first commit: immediately update number display
STR:
- do some scanning, then stop
- rotate device etc -> report count is zero

second commit: properly fix #1436

third commit: for debug builds, use the app debug name in the notification as well

### CODE REVIEW

File: android/src/main/java/org/mozilla/mozstumbler/client/navdrawer/MainDrawerActivity.java [hunk 1]
```diff
@@ -250,7 +250,7 @@ protected void onPostCreate(Bundle savedInstanceState) {
     @Override
     public void onPostResume() {
         super.onPostResume();
-        mMetricsView.update();
+        updateNumberDisplay(true);
```
Comment (crankycoder) [inline android/src/main/java/org/mozilla/mozstumbler/client/navdrawer/MainDrawerActivity.java:253]: Yay. Much nicer.

**Comment by crankycoder** [comment]
Thanks @cascheberg !
