### PR TITLE
Fix unlimited zoom

### LINKED ISSUE #1481: Limited zoom feature problems
@garvankeeley there are some more problems with #1463 / #1474 
- zooming out on low-res map becomes blank
- both res types do not show the MLS coverage anymore when zooming out too far
- I think the description text is not quite accurate. I suggest something like: zooming out can increase data usage (instead of conveying that the feature generally reduces data usage)

### LINKED ISSUE #1506: unlimited map zoom bug (tiles not visible)
we don't get MLS tiles above the limited zoom level (pls fix this) (I just see the map without the coverage tiles

-on the low resolution mode you don't see any map at all at a certain zoom level (just the circles on the map)

### PR DESCRIPTION
**Pull request by cascheberg**
First commit:
- cleanup some code
- make the full unlimited zoom mode apply only in high res mode

Second commit:
- add an additional coverage overlay that is used if zoom is lower than the current minimum coverage zoom level

Fixes #1506, fixes #1481

### CODE REVIEW

File: android/src/main/java/org/mozilla/mozstumbler/client/mapview/MapFragment.java [hunk 1]
```diff
@@ -90,6 +90,7 @@
     private LowResMapOverlay mLowResMapOverlayLowZoom;
     private Overlay mCoverageTilesOverlayLowZoom;
     private Overlay mCoverageTilesOverlayHighZoom;
+    private Overlay mCoverageTilesOverlayDefaultZoom;
```
Comment (garvankeeley) [inline android/src/main/java/org/mozilla/mozstumbler/client/mapview/MapFragment.java]: Hmm, not sure what to call this, but saying 'default' here is confusing. Unfortunately, "mCoverageTilesOverlayUnlimitedModeAtLowZoom" is the only thing I can think of :) that makes the purpose of this totally clear.

File: android/src/main/java/org/mozilla/mozstumbler/client/mapview/MapFragment.java [hunk 2]
```diff
@@ -267,6 +268,7 @@ private void initCoverageTiles(String coverageUrl) {
                 mRootView.getContext(), coverageUrl, mMap);
         mCoverageTilesOverlayHighZoom = new CoverageOverlay(CoverageOverlay.LowResType.HIGHER_ZOOM,
                 mRootView.getContext(), coverageUrl, mMap);
+        mCoverageTilesOverlayDefaultZoom = new CoverageOverlay(mRootView.getContext(), coverageUrl, mMap);
```
Comment (garvankeeley) [inline android/src/main/java/org/mozilla/mozstumbler/client/mapview/MapFragment.java]: Instead of another constructor, CoverageOverlay.TileResType.UNMODIFIED_ZOOM or ORIGINAL_ZOOM

File: android/src/main/java/org/mozilla/mozstumbler/client/mapview/MapFragment.java [hunk 3]
```diff
@@ -287,35 +289,37 @@ private void updateOverlayBaseLayer(int zoomLevel) {
...
     private void updateOverlayCoverageLayer(int zoomLevel) {
-        if (mCoverageTilesOverlayLowZoom == null || mCoverageTilesOverlayHighZoom == null) {
-            return;
-        }
-
         final List<Overlay> overlays = mMap.getOverlays();
-        int idx = 0;
-        if (overlays.indexOf(mLowResMapOverlayHighZoom) > -1 || overlays.indexOf(mLowResMapOverlayLowZoom) > -1) {
-            idx = 1;
+        if (mCoverageTilesOverlayLowZoom == null || mCoverageTilesOverlayHighZoom == null
```
Comment (garvankeeley) [inline android/src/main/java/org/mozilla/mozstumbler/client/mapview/MapFragment.java:304]: The precondition of this function should be the first line:
if (!isCoverageTilesInitialized()) {
  return;
}

File: android/src/main/java/org/mozilla/mozstumbler/client/mapview/tiles/CoverageOverlay.java [hunk 4]
```diff
@@ -16,18 +16,27 @@
  * This class provides the Mozilla Coverage overlay
  */
 public class CoverageOverlay extends AbstractMapOverlay {
+    public static final String MLS_MAP_TILE_COVERAGE_NAME = "Mozilla Location Service Coverage Map";
     // Use a lower zoom than the LowResMapOverlay, the coverage can be very low detail and still look ok
-    private static final int LOW_ZOOM_LEVEL = 10;
+    public static final int LOW_ZOOM_LEVEL = 10;
+
+    public CoverageOverlay(final Context aContext, final String coverageUrl, MapView mapView) {
```
Comment (garvankeeley) [inline android/src/main/java/org/mozilla/mozstumbler/client/mapview/tiles/CoverageOverlay.java]: See comment about changing the type to avoid another constructor.

File: android/src/main/java/org/mozilla/mozstumbler/client/mapview/tiles/CoverageOverlay.java [hunk 5]
```diff
@@ -16,18 +16,27 @@
...
+        super(aContext);
+        setup(1, AbstractMapOverlay.LARGE_SCREEN_MIN_ZOOM, coverageUrl, mapView);
```
Comment (garvankeeley) [inline android/src/main/java/org/mozilla/mozstumbler/client/mapview/tiles/CoverageOverlay.java]: Is the '1' correct?

File: android/src/main/java/org/mozilla/mozstumbler/client/mapview/tiles/CoverageOverlay.java [hunk 6]
```diff
@@ -16,18 +16,27 @@
...
     public CoverageOverlay(LowResType type, final Context aContext, final String coverageUrl, MapView mapView) {
         super(aContext);
 
         final int zoomLevel = (type == LowResType.HIGHER_ZOOM) ?
                 AbstractMapOverlay.getDisplaySizeBasedMinZoomLevel() : LOW_ZOOM_LEVEL;
+        setup(zoomLevel, zoomLevel, coverageUrl, mapView);
+    }
 
-        final ITileSource coverageTileSource = new XYTileSource("Mozilla Location Service Coverage Map",
+    private void setup(int aZoomMinLevel, int aZoomMaxLevel, final String coverageUrl, MapView mapView) {
```
Comment (garvankeeley) [inline android/src/main/java/org/mozilla/mozstumbler/client/mapview/tiles/CoverageOverlay.java]: no 'a' prefix (that is a Gecko C++ standard that we sometimes add accidentally AFAICT)

**Comment by garvankeeley** [comment]
r+ after nits addressed, thanks for fixing this!

File: android/src/main/java/org/mozilla/mozstumbler/client/mapview/MapFragment.java (hunk 1 above)
Comment (cascheberg) [inline android/src/main/java/org/mozilla/mozstumbler/client/mapview/MapFragment.java]: How about "OriginalZoom" and a comment?

Comment (garvankeeley) [inline android/src/main/java/org/mozilla/mozstumbler/client/mapview/MapFragment.java]: Sounds good.

File: android/src/main/java/org/mozilla/mozstumbler/client/mapview/tiles/CoverageOverlay.java (hunk 5 above)
Comment (cascheberg) [inline android/src/main/java/org/mozilla/mozstumbler/client/mapview/tiles/CoverageOverlay.java]: I just noticed that [zoom level 0](https://d17pt8qph6ncyq.cloudfront.net/tiles/0/0/0.png) is used as an image on the MLS website frontpage. But it is not available currently, and it wasn't when I checked before. Just a temporary server side issue?

Comment (garvankeeley) [inline android/src/main/java/org/mozilla/mozstumbler/client/mapview/tiles/CoverageOverlay.java]: I don't know, but I can't see needing it, isn't the unlimited zoom min level 3?

^^^ hold on, I am misreading the arguments

^^^^ no, I am not, I was expecting the setup values to be (3, 13), although using constants for these of course.

(I should re-read the code, I thought unlimited zoom was still limited to greater than 1 or 2)

Comment (cascheberg) [inline android/src/main/java/org/mozilla/mozstumbler/client/mapview/tiles/CoverageOverlay.java]: It's true that zoom levels lower than 3 will not be used currently. I was thinking that these parameters should just reflect the actual server side capability anyway (similar to `mHighResMapSource`).

Comment (garvankeeley) [inline android/src/main/java/org/mozilla/mozstumbler/client/mapview/tiles/CoverageOverlay.java]: Fair enough; It seems self-documenting as to how it will be used if those values are tied to zoom constants in the codebase, which I like as a reader. 
Aside: just noticed, isn't AbstractMapOverlay.LARGE_SCREEN_MIN_ZOOM too high for how this is used?

Comment (cascheberg) [inline android/src/main/java/org/mozilla/mozstumbler/client/mapview/tiles/CoverageOverlay.java]: Yes, the relevant range is only from `LOWEST_UNLIMITED_ZOOM` to `LOW_ZOOM_LEVEL - 1` (3 to 9). But as I said above, restricting the range at this part of the code seemed unnecessary to me. But I can change that if it improves code readability.

Comment (garvankeeley) [inline android/src/main/java/org/mozilla/mozstumbler/client/mapview/tiles/CoverageOverlay.java]: I vote yes, since when I look at in future, I'll know exactly for what zoom levels this is active from those values. Arguably, that is also in MapFragment, but that info is hard to see at a glance there.

**Comment by cascheberg** [comment]
@garvankeeley I updated the second commit to address your review comments.
